version: '2.4'
services:
    networkShare:
        container_name: network-share
        hostname:  network-share
        image: network-share
        restart: on-failure
        volumes:
            - /storage:/storage
        ports:
            - "445:445"
        networks:
            - nat
        environment:
            - MAIN_USER_PASSWORD=REPLACE_WITH_SMB_USER_PASSWORD
networks:
    nat:
        external: true