MusicFolder = "/storage/Music"
DataFolder = "/storage/Misc/Navidrome data"
Port = "4533"
EnableInsightsCollector = "false"
AutoTranscodeDownload = "false"
EnableArtworkUpload = "false"
EnableExternalServices = "false"
EnableReplayGain = "false"
EnableTranscodingCancellation = "true"
EnableTranscodingConfig = "true"
Scanner.Enabled = "true"
Scanner.ScanOnStartup = "true"
Scanner.PurgeMissing = "always"
TranscodingCacheSize = "0"